### ISSUE TITLE
Unknown error occurred during Mazda update request

### ISSUE THREAD

**Issue by Ghannes** [runDMCA/home-assistant-mazda#7] opened 2024-11-17 14:15 UTC
Integration ran fine for weeks but since yesterday I got:

This error originated from a custom integration.

Logger: custom_components.mazda
Source: custom_components/mazda/__init__.py:154
integration: Mazda Connected Services
First occurred: 3:03:01 PM (9 occurrences)
Last logged: 3:13:03 PM

Unknown error occurred during Mazda update request:
Traceback (most recent call last):
  File "/config/custom_components/mazda/__init__.py", line 57, in with_timeout
    return await task
           ^^^^^^^^^^
  File "/config/custom_components/mazda/pymazda/client.py", line 30, in get_vehicles
    vec_base_infos_response = await self.controller.get_vec_base_infos()
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mazda/pymazda/controller.py", line 30, in get_vec_base_infos
    return await self.connection.api_request(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mazda/pymazda/connection.py", line 191, in api_request
    return await self.__api_request_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mazda/pymazda/connection.py", line 221, in __api_request_retry
    return await self.__send_api_request(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mazda/pymazda/connection.py", line 329, in __send_api_request
    response = await self._session.request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 690, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 1058, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/streams.py", line 643, in read
    await self._waiter
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/mazda/__init__.py", line 154, in async_update_data
    vehicles = await with_timeout(mazda_client.get_vehicles())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mazda/__init__.py", line 56, in with_timeout
    async with asyncio.timeout(timeout_seconds):
  File "/usr/local/lib/python3.12/asyncio/timeouts.py", line 115, in __aexit__
    raise TimeoutError from exc_val
TimeoutError

**Comment by ArbnorMe** [comment] 2024-11-17 16:15
I've been having the same problem for a few days:


Dieser Fehler stammt von einer benutzerdefinierten Integration

Logger: custom_components.mazda
Quelle: custom_components/mazda/__init__.py:154
Integration: Mazda Connected Services
Erstmals aufgetreten: 17:05:43 (5 Vorkommnisse)
Zuletzt protokolliert: 17:09:04

Unknown error occurred during Mazda update request:
Traceback (most recent call last):
  File "/config/custom_components/mazda/__init__.py", line 57, in with_timeout
    return await task
           ^^^^^^^^^^
  File "/config/custom_components/mazda/pymazda/client.py", line 30, in get_vehicles
    vec_base_infos_response = await self.controller.get_vec_base_infos()
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mazda/pymazda/controller.py", line 30, in get_vec_base_infos
    return await self.connection.api_request(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mazda/pymazda/connection.py", line 191, in api_request
    return await self.__api_request_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mazda/pymazda/connection.py", line 221, in __api_request_retry
    return await self.__send_api_request(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mazda/pymazda/connection.py", line 329, in __send_api_request
    response = await self._session.request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 690, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 1059, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/streams.py", line 644, in read
    await self._waiter
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/mazda/__init__.py", line 154, in async_update_data
    vehicles = await with_timeout(mazda_client.get_vehicles())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mazda/__init__.py", line 56, in with_timeout
    async with asyncio.timeout(timeout_seconds):
  File "/usr/local/lib/python3.12/asyncio/timeouts.py", line 115, in __aexit__
    raise TimeoutError from exc_val
TimeoutError

**Comment by vonwerderc** [comment] 2024-11-17 22:58
Same error here: 

This error originated from a custom integration.

Logger: custom_components.mazda
Source: custom_components/mazda/__init__.py:154
integration: Mazda Connected Services
First occurred: November 16, 2024 at 9:40:22 PM (660 occurrences)
Last logged: 5:57:56 PM

Unknown error occurred during Mazda update request:
Traceback (most recent call last):
  File "/config/custom_components/mazda/__init__.py", line 57, in with_timeout
    return await task
           ^^^^^^^^^^
  File "/config/custom_components/mazda/pymazda/client.py", line 30, in get_vehicles
    vec_base_infos_response = await self.controller.get_vec_base_infos()
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mazda/pymazda/controller.py", line 30, in get_vec_base_infos
    return await self.connection.api_request(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mazda/pymazda/connection.py", line 191, in api_request
    return await self.__api_request_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mazda/pymazda/connection.py", line 221, in __api_request_retry
    return await self.__send_api_request(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mazda/pymazda/connection.py", line 329, in __send_api_request
    response = await self._session.request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 690, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 1059, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/streams.py", line 644, in read
    await self._waiter
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/mazda/__init__.py", line 154, in async_update_data
    vehicles = await with_timeout(mazda_client.get_vehicles())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mazda/__init__.py", line 56, in with_timeout
    async with asyncio.timeout(timeout_seconds):
  File "/usr/local/lib/python3.12/asyncio/timeouts.py", line 115, in __aexit__
    raise TimeoutError from exc_val
TimeoutError

**Comment by StephenMilner** [comment] 2024-11-18 08:41
Duplicate of Issue #5

**Comment by Ghannes** [comment] 2024-12-03 21:03
Duplicate

**Closed as completed** 2024-12-03 21:04 UTC
